/* BBCore.h — C core of the chess engine (position, move generation, castling,
 * en passant, FEN, repetition, perft). The hot paths are plain C so the
 * compiler can fully optimise them; the Objective-C layer wraps this core.
 */
#ifndef BBCore_h
#define BBCore_h

#include <stddef.h>
#include <stdint.h>

#include "BBTypes.h"

#ifdef __cplusplus
extern "C" {
#endif

#define BB_MAX_PLY 512

/* Undo record needed to roll back one makeMove call. */
typedef struct BBCoreUndo {
    uint64_t prevKey;
    int32_t  prevHalfmove;
    int32_t  prevKeyCount;
    int      prevCastle;
    BBMove   move;
    BBPiece  captured;     /* piece that was on the destination (BB_EMPTY if none) */
    BBSquare prevEp;
} BBCoreUndo;

/* Mutation-safe position core. All arrays are fixed-size; the position
 * history is bounded by BB_MAX_PLY (folded with make/unmake in search). */
typedef struct BBCore {
    BBPiece  squares[64];
    int      stm;              /* BB_WHITE or BB_BLACK */
    int      castle;           /* BB_CASTLE_* bitmask */
    BBSquare ep;               /* en passant target square, -1 when none */
    int32_t  halfmove;         /* halfmove clock (50-move rule) */
    int32_t  fullmove;         /* full move counter */
    uint64_t key;              /* current zobrist key */
    uint64_t keys[BB_MAX_PLY + 4];   /* zobrist history, keys[0] = start key */
    int32_t  keyCount;
    BBSquare kingPos[2];       /* index by BB_WHITE/BB_BLACK */
} BBCore;

/* Zobrist tables. Built lazily when the first board is initialised. */
void bbZobristInit(void);

/* Seed the PRNG that derives the Zobrist tables (default fixed seed). */
void bbZobristSetSeed(uint64_t seed);

/* Initialise *b from a FEN string. NULL/empty means the start position. */
void bbCoreInit(BBCore *b, const char *fen);

/* Copy src into dst. */
void bbCoreCopy(BBCore *dst, const BBCore *src);

/* Make a (pseudo-legal, fully legal when generated by bbGenLegal) move. */
void bbCoreMake(BBCore *b, BBMove move, BBCoreUndo *undo);

/* Undo the move recorded in undo (must be the last applied to b). */
void bbCoreUnmake(BBCore *b, const BBCoreUndo *undo);

/* Null move (pass): flips the side to move without moving a piece. Used by
 * null-move pruning in the search. */
void bbCoreMakeNull(BBCore *b, BBCoreUndo *undo);
void bbCoreUnmakeNull(BBCore *b, const BBCoreUndo *undo);

/* Whether the side to move is in check. */
int bbInCheck(const BBCore *b);

/* Whether 'color' (BB_WHITE/BB_BLACK) is in check in the given position.
 * Used for move-legality testing, where post-make state has the opponent
 * to move. */
int bbInCheckSide(const BBCore *b, int color);

/* Whether sq is attacked by any piece of color 'byColor' (BB_WHITE/BLACK). */
int bbSquareAttacked(const BBCore *b, BBSquare sq, int byColor);

/* Pseudo-legal move generation into out[]. Returns the move count.
 * out must hold at least 256 entries. */
int bbGenPseudo(const BBCore *b, BBMove *out);

/* Fully legal move generation (drops moves that leave own king en prise).
 * out must hold at least 256 entries. Returns the move count. */
int bbGenLegal(const BBCore *b, BBMove *out);

/* True when the side to move has at least one legal move. */
int bbHasLegal(const BBCore *b);

/* Number of squares attacked by piece at 'from' (empty or enemy squares
 * only). Used by the evaluator's mobility term. */
int bbLitMoves(const BBCore *b, BBSquare from, BBPiece piece);

/* Draw-result predicates (threefold repetition, 50-move rule, insufficient
 * material). Returns 1 when the position is an immediate draw. */
int bbIsRepetition(const BBCore *b);
int bbIsFiftyMove(const BBCore *b);
int bbInsufficientMaterial(const BBCore *b);

/* Is the side-to-move position checkmate? (Requires no legal moves.) */
int bbIsCheckmate(const BBCore *b);

/* Full perft (move generator validation). */
int64_t bbPerft(BBCore *b, int depth);

/* Serialise the position to FEN (caller provides buffer). */
void bbToFen(const BBCore *b, char *out, size_t outSize);

/* Serialise a move to UCI notation ("e2e4", "e7e8q", "e1g1"). */
void bbMoveToUci(BBMove move, char *out, size_t outSize);

/* Serialise a legal move to SAN notation ("Nf3", "exd5", "O-O", "e8=Q+",
 * with disambiguation and check/mate suffix). Caller provides buffer. */
void bbMoveToSan(const BBCore *b, BBMove move, char *out, size_t outSize);

/* Parse a SAN token ("Nf3", "exd5", "O-O", "e8=Q", with or without a
 * trailing '+'/'#') against the current position. Returns nonzero and sets
 * *out on a unique legal match. */
int bbParseSan(const BBCore *b, const char *san, BBMove *out);

/* Game-status word for the current position into out ("active", "check",
 * "checkmate <white|black>", "stalemate", "draw"). Caller provides buffer. */
void bbGameStatus(const BBCore *b, char *out, size_t outSize);

/* Parse a UCI move token ("e2e4", "e7e8q") against the current position.
 * Returns nonzero and sets *out on success. */
int bbParseUciMove(const BBCore *b, const char *token, BBMove *out);

#ifdef __cplusplus
}
#endif

#endif /* BBCore_h */