name: Fly Deploy

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
    branches:
      - main # Or your default branch

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' # Only run if the test workflow succeeded
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
