name: Run Tests

on:
  push:
    branches: [ "main" ] # Or your default branch
  pull_request:
    branches: [ "main" ] # Or your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Match your project's Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Install NLTK data required by your bot
        python -m nltk.downloader punkt wordnet averaged_perceptron_tagger

    - name: Run pytest
      run: pytest
